import type { ReportRecord } from "@reprorelay/shared";

export interface PersonPresentation {
  name: string;
  email?: string;
  avatarUrl?: string;
  team?: string;
  customerSince?: string;
  company?: string;
  plan?: string;
  ticketSummary?: string;
}

export interface ActivityPresentation {
  label: string;
  detail?: string;
  time: string;
  kind: "report" | "ai" | "assignment" | "review";
}

export interface AttachmentPresentation {
  id: string;
  title: string;
  meta?: string;
  time?: string;
  kind: "text" | "data" | "image" | "video";
  url?: string;
}

export interface VideoPresentation {
  url: string;
  contentType: string;
}

export interface DuplicatePresentation {
  id: string;
  title: string;
  confidence: string;
}

export interface NotePresentation {
  author: PersonPresentation;
  createdLabel: string;
  body: string;
  channel?: "note" | "email";
  providerId?: string;
}

export interface SavedViewPresentation {
  label: string;
  count: number;
}

export interface ReportPresentation {
  mode: "live" | "showcase";
  workspaceName: string;
  areaName?: string;
  reportNumber: string;
  createdLabel: string;
  reporter: PersonPresentation;
  currentUser: PersonPresentation;
  notificationCount?: number;
  deploymentVersion?: string;
  assignee?: PersonPresentation;
  team?: string;
  tags: string[];
  slaDue?: string;
  releaseLabel?: string;
  environmentLabel: string;
  browserLabel: string;
  platformLabel: string;
  aiSummary: string[];
  /** Ready-to-copy fix prompt for an AI coding agent, generated by triage. */
  agentPrompt?: string;
  internalNotes: NotePresentation[];
  defaultReply: string;
  evidence: {
    capturedLabel: string;
    screenshotUrl?: string;
    screenshotAlt: string;
    steps: string[];
    errorSignal?: string;
    attachments: AttachmentPresentation[];
    video?: VideoPresentation;
  };
  duplicates: DuplicatePresentation[];
  activity: ActivityPresentation[];
}

export interface SessionUser {
  id: string;
  email: string;
  name: string;
}

export interface SessionCheck {
  authenticated: boolean;
  user?: SessionUser;
}

export interface LoginInput {
  email?: string;
  password: string;
}

export interface ProjectInfo {
  projectKey: string;
  name: string;
  origins: string[];
  githubRepo?: string;
  createdAt: string;
}

export interface GitHubStatus {
  connected: boolean;
  slug?: string;
  name?: string;
  htmlUrl?: string;
  manageUrl?: string;
}

export interface EmailStatus {
  configured: boolean;
  from?: string;
  replyTo?: string;
}

export interface TeamUser {
  id: string;
  email: string;
  name: string;
  createdAt: string;
}

export interface DashboardDataSource {
  mode: "live" | "showcase";
  requiresAuthentication?: boolean;
  /** Base URL of the API, used to render embed snippets for projects. */
  apiUrl?: string;
  checkSession?(): Promise<SessionCheck>;
  login?(input: LoginInput): Promise<void>;
  logout?(): Promise<void>;
  fetchReports(): Promise<ReportRecord[]>;
  updateReport(id: string, patch: Partial<ReportRecord>): Promise<ReportRecord>;
  addNote(id: string, body: string): Promise<ReportRecord>;
  sendReply(id: string, body: string): Promise<ReportRecord>;
  requestGitHubIssue(id: string): Promise<ReportRecord>;
  requestEngineeringHandoff?(id: string): Promise<ReportRecord>;
  updateReporterEmail?(id: string, email: string): Promise<ReportRecord>;
  archiveReport?(id: string): Promise<ReportRecord>;
  restoreReport?(id: string): Promise<ReportRecord>;
  emailStatus?(): Promise<EmailStatus>;
  present(report: ReportRecord): ReportPresentation;
  savedViews(reports: ReportRecord[]): SavedViewPresentation[];
  listProjects?(): Promise<ProjectInfo[]>;
  createProject?(input: { name: string; origin?: string }): Promise<ProjectInfo>;
  updateProject?(projectKey: string, patch: { githubRepo?: string | null }): Promise<ProjectInfo>;
  deleteProject?(projectKey: string): Promise<void>;
  githubStatus?(): Promise<GitHubStatus>;
  listGitHubRepos?(): Promise<string[]>;
  disconnectGitHub?(): Promise<void>;
  /** Path (relative to apiUrl) that starts the GitHub connect flow. */
  githubConnectPath?: string;
  listUsers?(): Promise<TeamUser[]>;
  createUser?(input: { email: string; name: string; password: string }): Promise<TeamUser>;
  deleteUser?(id: string): Promise<void>;
}

export class EmailNotConfiguredError extends Error {
  constructor() {
    super("Email replies aren't configured for this deployment.");
    this.name = "EmailNotConfiguredError";
  }
}

export function formatDateTime(value: string): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

export function projectName(projectKey: string): string {
  return projectKey
    .replace(/^proj_/, "")
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(" ");
}
