import type { ReportRecord } from "./schemas.js";

export const demoReports: ReportRecord[] = [
  {
    id: "018ff3ef-f9dd-7c29-a648-d8dd59a9b001",
    sessionId: "018ff3ef-f9dd-7c29-a648-d8dd59a9b101",
    projectKey: "proj_prime-connect",
    title: "Template preview is blank after selecting a contact group",
    comment: "I chose the July offer template and then selected the Gold customers group. The preview panel went blank and I could not send the message.",
    severity: "high",
    user: { id: "client-1", email: "sarah.chen@example.com", name: "Sarah Chen" },
    release: "2026.07.09",
    environment: "staging",
    browser: {
      url: "https://client.example.com/campaigns/new",
      title: "Create Campaign",
      userAgent: "Mozilla/5.0 Chrome/126",
      viewport: { width: 1440, height: 960, devicePixelRatio: 2 },
      language: "en-GB",
      timezone: "Europe/London",
    },
    breadcrumbs: [
      { type: "route", message: "/campaigns/new", timestamp: "2026-07-09T09:10:10.000Z" },
      { type: "click", message: "button: July offer", timestamp: "2026-07-09T09:10:14.000Z" },
      { type: "click", message: "select: Gold customers", timestamp: "2026-07-09T09:10:22.000Z" },
    ],
    console: [
      { level: "error", message: "Cannot read properties of undefined (reading 'variables')", timestamp: "2026-07-09T09:10:23.000Z" },
    ],
    network: [
      { method: "GET", url: "https://api.example.com/templates/tpl_123", status: 200, durationMs: 91 },
      { method: "POST", url: "https://api.example.com/preview", status: 500, durationMs: 642 },
    ],
    replayEvents: [],
    assets: [
      { kind: "screenshot", objectKey: "demo/blank-preview.png", contentType: "image/png", url: "https://placehold.co/900x540" },
    ],
    context: { accountId: "acct_demo" },
    createdAt: "2026-07-09T09:10:30.000Z",
    status: "triaged",
    agentStatus: "needs_review",
    aiTriage: {
      provider: "reprorelay-local-triage",
      generatedAt: "2026-07-09T09:10:31.000Z",
      summary:
        "Client reported a blank template preview after selecting a contact group. Primary console signal: Cannot read properties of undefined (reading 'variables'). Primary network signal: POST https://api.example.com/preview returned 500.",
      likelyArea: "backend",
      severityRecommendation: "high",
      confidence: 0.9,
      reproductionSteps: ["Navigate to /campaigns/new.", "Interact with button: July offer.", "Interact with select: Gold customers."],
      keySignals: [
        "Console error: Cannot read properties of undefined (reading 'variables')",
        "Failed request: POST https://api.example.com/preview -> 500",
        "Screenshot attached.",
        "Release: 2026.07.09.",
      ],
      suggestedLabels: ["area:backend", "severity:high", "env:staging", "source:reprorelay", "needs:human-review"],
      suggestedTests: [
        "Regression test for the reported workflow on /campaigns/new.",
        "API should return a typed error response for the failing request.",
        "UI should show a recoverable error state instead of failing silently.",
      ],
      agentPrompt:
        "Human-approved agent task:\n\nInvestigate the ReproRelay report \"Template preview is blank after selecting a contact group\".\nLikely area: backend. Severity recommendation: high.\n\nProduce the smallest safe fix and include a regression test where practical.",
      safetyNotes: [
        "Human review is required before any coding agent handoff.",
        "Do not paste private client data, credentials, cookies, tokens, or payment details into public agent comments.",
      ],
      requiresHumanReview: true,
    },
    humanReview: { status: "pending", agentHandoffApproved: false },
    notes: [],
  },
  {
    id: "018ff3ef-f9dd-7c29-a648-d8dd59a9b002",
    sessionId: "018ff3ef-f9dd-7c29-a648-d8dd59a9b102",
    projectKey: "proj_estates",
    title: "Property search filters reset on mobile",
    comment: "When I set min bedrooms and go back from a listing, the filters are gone.",
    severity: "medium",
    user: { id: "client-2", email: "manager@example.com", name: "Lettings Manager" },
    release: "2026.07.08",
    environment: "production",
    browser: {
      url: "https://client.example.com/properties?beds=3",
      title: "Properties",
      userAgent: "Mozilla/5.0 Safari/605",
      viewport: { width: 390, height: 844, devicePixelRatio: 3 },
      language: "en-GB",
      timezone: "Europe/London",
    },
    breadcrumbs: [
      { type: "click", message: "filter: 3 bedrooms", timestamp: "2026-07-09T08:20:01.000Z" },
      { type: "click", message: "listing: High Street", timestamp: "2026-07-09T08:20:09.000Z" },
      { type: "route", message: "/properties/high-street", timestamp: "2026-07-09T08:20:10.000Z" },
      { type: "click", message: "browser back", timestamp: "2026-07-09T08:20:31.000Z" },
    ],
    console: [],
    network: [{ method: "GET", url: "https://api.example.com/properties", status: 200, durationMs: 128 }],
    replayEvents: [],
    assets: [],
    createdAt: "2026-07-09T08:20:40.000Z",
    status: "new",
    agentStatus: "pending",
    notes: [],
  },
];
